// Bundles the MCP server (packages/mcp + core + the edge client) into one plain-JS Vercel Function:
// packages/web/api/mcp.js. Committed on purpose, so Vercel serves it without compiling TypeScript
// from other workspace packages. `pnpm test` fails if it's out of date: run `pnpm mcp:build`.
import { build } from "esbuild";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("../", import.meta.url));
export const OUT = `${root}packages/web/api/mcp.js`;

export async function bundle() {
  const r = await build({
    entryPoints: [`${root}packages/mcp/src/vercel.ts`],
    bundle: true,
    platform: "node",
    format: "esm",
    target: "node20",
    write: false,
    absWorkingDir: root, // keeps the "// path" comments the same wherever it's run from
    legalComments: "none",
    logLevel: "silent",
    banner: { js: "// Generated by scripts/build-mcp.mjs from packages/mcp — do not edit. Rebuild: pnpm mcp:build" },
  });
  return r.outputFiles[0].text;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const code = await bundle();
  const before = (() => { try { return readFileSync(OUT, "utf8"); } catch { return ""; } })();
  writeFileSync(OUT, code);
  console.log(`${before === code ? "unchanged" : "wrote"} ${OUT} (${(code.length / 1024).toFixed(0)} KB)`);
}
