// Copies the shared tool schemas and the Markdown prompts into the Deno function.
// /prompts and packages/core/src/schemas.ts stay the source of truth; the copies are gitignored.
import { copyFileSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("../", import.meta.url));
const fn = `${root}packages/edge/supabase/functions/pipeline/`;

mkdirSync(`${fn}_core`, { recursive: true });
mkdirSync(`${fn}prompts`, { recursive: true });
copyFileSync(`${root}packages/core/src/schemas.ts`, `${fn}_core/schemas.ts`);

const prompts = {};
for (const f of readdirSync(`${root}prompts`).filter((f) => f.endsWith(".md"))) {
  copyFileSync(`${root}prompts/${f}`, `${fn}prompts/${f}`);
  prompts[f.replace(/\.md$/, "")] = readFileSync(`${root}prompts/${f}`, "utf8");
}
// Fallback bundle for runtimes that don't ship static files; the function prefers the .md files.
writeFileSync(
  `${fn}_core/prompts.ts`,
  `// Generated by scripts/sync-edge.mjs from /prompts — do not edit.\nexport const BUNDLED_PROMPTS: Record<string, string> = ${JSON.stringify(prompts, null, 2)};\n`,
);
console.log(`synced schemas + ${Object.keys(prompts).length} prompts → ${fn}`);
